name: Build as-authentication CI

on: 
  push:
    branches: [ master ]

jobs:
  build-as-authentication:
    runs-on: ubuntu-latest
    name: Building as-authentication
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: awesome-sphere/as-ci-cd-template@v1
        with:
          repo: as-authentication
          token: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY: ghcr.io
          BASE_IMG_NAME: ${{ github.repository }}